process.loadEnvFile();

const {
  MINIO_PORT,
  MINIO_HOST,
  MINIO_BUCKET_NAME,
  MINIO_ACCESS_KEY,
  MINIO_SECRET_KEY,
  MINIO_ROOT_USER,
  MINIO_ROOT_PASSWORD,

  MINIO_PORT_DEVELOPMENT,
  MINIO_HOST_DEVELOPMENT,
  MINIO_BUCKET_NAME_DEVELOPMENT,
  MINIO_ACCESS_KEY_DEVELOPMENT,
  MINIO_SECRET_KEY_DEVELOPMENT,
  MINIO_ROOT_USER_DEVELOPMENT,
  MINIO_ROOT_PASSWORD_DEVELOPMENT,
} = process.env;

export const config = {
  development: {
    port: MINIO_PORT_DEVELOPMENT,
    host: MINIO_HOST_DEVELOPMENT,
    bucket_name: MINIO_BUCKET_NAME_DEVELOPMENT,
    access_key: MINIO_ACCESS_KEY_DEVELOPMENT,
    secret_key: MINIO_SECRET_KEY_DEVELOPMENT,
    root_user: MINIO_ROOT_USER_DEVELOPMENT,
    root_password: MINIO_ROOT_PASSWORD_DEVELOPMENT,
  },
  production: {
    port: MINIO_PORT,
    host: MINIO_HOST,
    bucket_name: MINIO_BUCKET_NAME,
    access_key: MINIO_ACCESS_KEY,
    secret_key: MINIO_SECRET_KEY,
    root_user: MINIO_ROOT_USER,
    root_password: MINIO_ROOT_PASSWORD,
  },
};
