import seedBrand from "@brands-seeders/brand.seeder";
import seedCategories from "@categories-seeders/category.seeder";
import seedDetails from "@products-seeders/detail.seeder";
import seedProducts from "@products-seeders/product.seeder";
import seedSizes from "@sizes-seeders/size.seeder";
import seedUsers from "@users-seeders/user.seeder";
import { Models } from "@models";
import seedDebt from "./seedDebt";
import seedExpenses from "./seedExpenses";
import seedFinancialAccounts from "./seedFinancialAccounts";
import seedFinancialAccountsPaymentMethods from "./seedFinancialAccountsPaymentMethods";
import seedInstallment from "./seedInstallment";
import seedMovements from "./seedMovements";
import seedPaymentMethods from "./seedPaymentMethod";

export const seedDatabase = async (models: Models) => {
  await seedUsers(models);
  await seedCategories(models);
  await seedSizes(models);
  await seedProducts(models);
  await seedBrand(models);
  await seedDetails(models);
  await seedPaymentMethods(models);
  await seedFinancialAccounts(models);
  await seedFinancialAccountsPaymentMethods(models);
  await seedExpenses(models);
  await seedDebt(models);
  await seedInstallment(models);
  await seedMovements(models);
};
