import seedBrand from "@brands-seeders/brand.seeder";
import seedCategories from "@categories-seeders/category.seeder";
import seedDetails from "@products-seeders/detail.seeder";
import seedProducts from "@products-seeders/product.seeder";
import seedUsers from "@users-seeders/user.seeder";
import seedSizes from "@sizes-seeders/size.seeder";
import seedFinancialAccounts from "@accounts-seeders/account.seeder";
import seedFinancialAccountsPaymentMethods from "@accounts-seeders/accounts-payment-methods.seeder";
import seedExpenses from "@expense-seeders/expenses.seeder";
import seedMovements from "@movement-seeders/movement.seeder";
import seedPaymentMethods from "@payment-methods-seeders/payment-method.seeder";
import seedDebt from "@debt-seeders/debts.seeder";
import seedInstallment from "@debt-seeders/installment.seeder";
import { Models } from "@models";

export const seedDatabase = async (models: Models) => {
  await seedUsers(models);
  await seedCategories(models);
  await seedSizes(models);
  await seedProducts(models);
  await seedBrand(models);
  await seedDetails(models);
  await seedPaymentMethods(models);
  await seedFinancialAccounts(models);
  await seedFinancialAccountsPaymentMethods(models);
  await seedExpenses(models);
  await seedDebt(models);
  await seedInstallment(models);
  await seedMovements(models);
};
